language: php

sudo: false

matrix:
  include:
    - php: hhvm
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - composer --prefer-source update

script:
    - vendor/bin/phpunit
