##
 # This file is part of the Toggler package.
 #
 # (c) SolidWorx <open-source@solidworx.co>
 #
 # For the full copyright and license information, please view the LICENSE
 # file that was distributed with this source code.
 ##

services:
    toggler.twig.extension:
        class: Toggler\Twig\Extension\ToggleExtension
        tags:
            - { name: twig.extension }