##
 # This file is part of the Toggler package.
 #
 # (c) SolidWorx <open-source@solidworx.co>
 #
 # For the full copyright and license information, please view the LICENSE
 # file that was distributed with this source code.
 ##

services:
    toggler.toggle:
        class: SolidWorx\Toggler\Toggle
        arguments: ['?']

    toggler.twig.extension:
        class: SolidWorx\Toggler\Twig\Extension\ToggleExtension
        arguments: ['@toggler.toggle']
        tags:
            - { name: twig.extension }