##
 # This file is part of the Toggler package.
 #
 # (c) SolidWorx <open-source@solidworx.co>
 #
 # For the full copyright and license information, please view the LICENSE
 # file that was distributed with this source code.
 ##

services:
    _defaults:
        autowire: true
        autoconfigure: true

    SolidWorx\Toggler\Symfony\Command\:
        resource: '../../Command/'

    SolidWorx\Toggler\Symfony\Command\ToggleSetCommand:
        arguments: ['?']

    SolidWorx\Toggler\Symfony\Command\ToggleGetCommand:
        arguments:
            $toggle: '@SolidWorx\Toggler\Toggle'

    Symfony\Component\DependencyInjection\ExpressionLanguageProvider:
        public: false

    Symfony\Component\Security\Core\Authorization\ExpressionLanguageProvider:
        public: false

    Symfony\Component\ExpressionLanguage\ExpressionLanguage:
        public: false
        calls:
            - ['registerProvider', ['@Symfony\Component\DependencyInjection\ExpressionLanguageProvider']]
            - ['registerProvider', ['@Symfony\Component\Security\Core\Authorization\ExpressionLanguageProvider']]

    SolidWorx\Toggler\Toggle:
        arguments: ['?', '@Symfony\Component\ExpressionLanguage\ExpressionLanguage']

    SolidWorx\Toggler\Symfony\Toggle:
        decorates: 'SolidWorx\Toggler\Toggle'
        public: false
        arguments:
            $toggle: '@SolidWorx\Toggler\Symfony\Toggle.inner'
        calls:
            - ['setContainer', ['@service_container']]

    SolidWorx\Toggler\Twig\Extension\ToggleExtension:
        arguments: ['@Solidworx\Toggler\Toggle']
        tags:
            - { name: twig.extension }